### ISSUE TITLE
Cross compile for RISC-V issue

### ISSUE THREAD

**Issue by 0xStuart** [cminyard/ser2net#106]
I am trying to cross compile for RISC-V

```
./configure --host=riscv64-linux-gnu --prefix=/build-libs
...
checking gensio/gensio.h usability... yes
checking gensio/gensio.h presence... yes
checking for gensio/gensio.h... yes
checking for str_to_gensio in -lgensio... no
configure: error: libgensio won't link, please install gensio dev package
```

config.log
```
...
/duo-sdk/riscv64-linux-musl-x86_64/bin/../lib/gcc/riscv64-unknown-linux-musl/10.2.0/../../../../riscv64-unknown-linux-musl/bin/ld: warning: libgensioosh.so.6, needed by /build-libs/lib/libgensio.so, not found (try using -rpath or -rpath
-link)
'''
```
The file is there.
```
ls -la /build-libs/lib/libgensioosh.so.6
lrwxrwxrwx 1 root root 21 Oct 28 21:50 /build-libs/lib/libgensioosh.so.6 -> libgensioosh.so.6.0.0
```

```
echo $LDFLAGS
-mcpu=c906fdv -march=rv64imafdcv0p7xthead -mcmodel=medany -mabi=lp64d -L/build-libs/lib

echo $LD_LIBRARY_PATH
/build-libs/lib
```

**Comment by cminyard** [comment]
Is /build-libs/lib in /etc/ld.so.conf or a file in /etc/ld/so.conf.d/?  When you put libraries in strange places it can cause issues.

**Comment by 0xStuart** [comment]
ldconfig complains if you add libs for a different architecture.
It's running in a GitHub build container.  It compiles openssl, libyaml, gensio, then fails at ser2net. :(

**Comment by cminyard** [comment]
On Mon, Nov 06, 2023 at 04:50:56PM -0800, Stuart wrote:
> ldconfig complains if you add libs for a different architecture.
> It's running in a GitHub build container.  It compiles openssl, libyaml, gensio, then fails at ser2net. :(

I'm not really sure.  I'd need access to the system or some way to
reproduce to work on this.

**Comment by 0xStuart** [comment]
I'm using a Milk-V Duo RISC-V board. There is a docker image to assist compiling apps, called duo-sdk-docker which is your base image.  I wrote the following Dockerfile to compile ser2net:


```
FROM ghcr.io/logicethos/duo-sdk-docker:latest

# Build OpenSSL
RUN wget https://www.openssl.org/source/openssl-1.1.1l.tar.gz \
    && tar -xzf openssl-1.1.1l.tar.gz \
    && cd openssl-1.1.1l \
    && ./Configure linux64-riscv64 shared no-asm --prefix=$BUILD_OUTPUT \
    && make && make install

# Build libyaml
WORKDIR /
RUN git clone https://github.com/yaml/libyaml
WORKDIR /libyaml
RUN ./bootstrap
RUN ./configure --host=riscv64-linux-gnu --prefix=$BUILD_OUTPUT \
    && make && make install

# Build gensio
WORKDIR /
RUN git clone https://github.com/cminyard/gensio.git
WORKDIR /gensio
RUN sh reconf
RUN ./configure --host=riscv64-linux-gnu --prefix=$BUILD_OUTPUT \
    && make && make install

## Build ser2net
WORKDIR /
RUN git clone https://github.com/cminyard/ser2net.git
WORKDIR /ser2net
RUN sh reconf
RUN ./configure --host=riscv64-linux-gnu --prefix=$BUILD_OUTPUT \
    && make && make install

CMD bash
```
It fails at the last RUN.

**Comment by cminyard** [comment]
On Tue, Nov 07, 2023 at 06:56:38AM -0800, Stuart wrote:
> I'm using a Milk-V Duo RISC-V board. There is a docker image to assist compiling apps, called duo-sdk-docker which is your base image.  I wrote the following Dockerfile to compile ser2net:

I don't have a RISC-V board, but I think I know what's going on.

That's not going to work as you've done it.  You would have to install
the images in a place where the new packages can find them.  For
instance, I did something similar to you in a debian docker image and
got the following when compiling gensio:

Gensios:
...
  mdns:		 no
  sound:	 dynamic
  cm108gpio:	 no
  ssl:		 no
  certauth:	 no

As you can see, it didn't find ssl, even though it's there in
/build-lib.  I'm guessing you have to do some sort of multi-stage thing
where you build each package into its own image.  Or something else.

I'm actually kind of surprised you need to build openssl, isn't it there
in the image?

Anyway, the problem really isn't with ser2net, the problem is with how
you are building it.  I don't know enough about these procedures to help
you, but I suggest you ask the person responsible for that docker image.

**Comment by 0xStuart** [comment]
OK thanks.

The Milk-V Duo is a $9 board which runs Linux.  As it has 4 usable UARTS & built in Ethernet, so it will make an excellent remote interface.

I'm trying to build all the tools you might need, like ser2net, MODBUS bridges etc using GitHub build pipeline (which is x86) hence the need to compile openssl to RISC-V.  That's why the libs are compiled to a non-standard location.

**Comment by 0xStuart** [comment]
Fixed! I had to add  `-rpath-link,$BUILD_OUTPUT/lib` to LDFLAGS.
