### ISSUE TITLE
RTS pin triggers unexpectedly

### ISSUE THREAD

**Issue by pieterverberne** [cminyard/ser2net#132]
For a testing application we are using ser2net to connect to serial consoles, and we are using the RTS pin (via an optocoupler) to "press" a button on the device. Sometimes, when connecting to ser2net, we see a 'button released' message on the console. This tells me that the RTS pin must have gone low and high again. This only happens on the _first_ connection to ser2net. Subsequent, and simultaneously connections to the same port don't trigger the RTS toggle. Until I disconnect all ser2net sessions and connect a new ser2net session, than, RTS is triggered again. 

```
define: &banner ser2net port \p device \d [\B] end ser2net banner\r\n\r\n

admin:  
    accepter: tcp,4999

connection: &con5000  
    accepter: telnet(rfc2217),tcp,5000  
    timeout: 1800  
    enable: on  
    options:  
      banner: *banner  
      kickolduser: true  
      max-connections: 100  
      telnet-brk-on-sync: true  
    connector: serialdev,/dev/ttyDUT0,115200n81,local,hangup-when-done=0
```

We are using this console cable:
Future Technology Devices International, Ltd FT232 Serial (UART) IC

Maybe it is a hardware issue. Troubleshooting tips are welcome :-)

**Comment by cminyard** [comment]
On Tue, Sep 10, 2024 at 4:12 AM pieterverberne ***@***.***>
wrote:

> For a testing application we are using ser2net to connect to serial
> consoles, and we are using the RTS pin (via an optocoupler) to "press" a
> button on the device. Sometimes, when connecting to ser2net, we see a
> 'button released' message on the console. This tells me that the RTS pin
> must have gone low and high again. This only happens on the *first*
> connection to ser2net. Subsequent, and simultaneously connections to the
> same port don't trigger the RTS toggle. Until I disconnect all ser2net
> sessions and connect a new ser2net session, than, RTS is triggered again.
>

Yeah, that's not a surprise.  When ser2net opens a serial port, it has to
open it first then set it up.  Depending on what the settings of the device
are before the open, it could cause RTS to toggle very quickly between the
open and the configuration.  ser2net will restore the original
configuration before it closes the port, so the next time it opens it will
do the same thing.  And ser2net will close the port when all sessions
disconnect, just as you are seeing.

Look at the configuration of the port with "stty -a </dev/tty..." without
ser2net running.  I think you know the settings, -hupcl, clocal, -ctsrts,
at least.  You can use stty to configure the default settings of the port.
Of course, it will suffer the same issue the first time you use it, but it
will then be set until the system reboots.

If that doesn't help, it may be a driver or hardware issue.  I just
re-looked over the ser2net code and I don't think the issue is there, but
subtle things can happen.  Also, you don't mention the ser2net version or
what OS and version you are using.

-corey

**Comment by pieterverberne** [comment]
I found the exact same issue when using cu to connect to /dev/ttyUSB0 : rts is triggerd. I'm trying various settings with stty but they don't seem to take any effect. Maybe because I'm using a usb UART cable.

Thanks for pointing in the right direction.

**Comment by cminyard** [comment]
On Wed, Sep 11, 2024 at 4:48 AM pieterverberne ***@***.***> wrote:
>
> I found the exact same issue when using cu to connect to /dev/ttyUSB0 : rts is triggerd. I'm trying various settings with stty but they don't seem to take any effect. Maybe because I'm using a usb UART cable.
>
> Thanks for pointing in the right direction.

So I did a little experiment.  I have a simulated serial port that I
used for testing.  I added a print of the RTS value where the modem
control lines are set and where the termios set CRTSCTS.  I did a
"stty -a </dev/ttyEcho0" on a simulated port:

2024-09-11T13:09:39.480934-05:00 dell1 kernel: termios: 0
2024-09-11T13:09:39.480949-05:00 dell1 kernel: mctl: 4
2024-09-11T13:09:39.482927-05:00 dell1 kernel: mctl: 0

You can see that Linux itself is raising and lowering RTS on its own.
So I'm guessing the problem is not the hardware, but it's in the Linux
serial code.  I traced this down, and it seems to be wrapped around
hupcl.

So, if I do "stty -hupcl </dev/ttyEcho0", then I use the serial port
parameters "local,hangup-when-done=no", it doesn't seem to modify the
RTS value any more when the device is opened and closed.  The RTS line
seems to be set to be driven and doesn't change.

Hopefully that helps.  If that doesn't work, it's probably the hardware.

**Comment by pieterverberne** [comment]
It looks like setting hangup-when-done=no does indeed fix the issue!

Thanks a lot!
