### ISSUE TITLE
Will ser2net work with Windows 10 WSL?

### ISSUE THREAD

**Issue by rin67630** [cminyard/ser2net#23]
I could not find any trace of someone who succeeded / failed with using ser2net under Windows Subsystem Linux?
Is is doable?

**Comment by cminyard** [comment]
On Thu, Feb 20, 2020 at 02:13:55PM -0800, RIN67630 wrote:
> I could not find any trace of someone who succeeded / failed with using ser2net under Windows Subsystem Linux?
> Is is doable?

Probably not.  Well, you probably can't use hardware serial ports from
WSL.  ser2net can do a lot more than that now.

You should be able to port ser2net to Windows.  I don't have any real
experience with windows, so I don't know how hard it would be, but I've
been wondering if someone would do it some day.  ser2net and gensio were
written to be portable; I doubt you would have to do any substantial
code changes outside of the selector code and the gensio_osops file.

-corey

**Comment by rin67630** [comment]
Hmm Windows Subsystem Linux IS a Linux System, and ser2net installs without issuing errors
The caveat is that the ports have a different naming convention and the kernel is a different one.
E.g se2net does not wok with pseudo terminals /dev/pty... either, it issues no warning, just does not work.

**Comment by cminyard** [comment]
On Sun, Feb 23, 2020 at 01:22:24AM -0800, RIN67630 wrote:
> Hmm Windows Subsystem Linux IS a Linux System, and ser2net installs without issuing errors

Well, no, per wikipedia, at least: Windows Subsystem for Linux (WSL) is
a compatibility layer for running Linux binary executables (in ELF
format) natively on Windows 10 and Windows Server 2019.

> The caveat is that the ports have a different naming convention and the kernel is a different one.
> E.g se2net does not wok with pseudo terminals /dev/pty... either, it issues no warning, just does not work. 

Yeah, I expected it to install and kind of work.  I didn't expect serial
ports and such to work.  But maybe?  Perhaps the compatibility layers
handle all that.  ptys may not work due to some semantic differences.
Not sure, it would take some debugging.

-corey

**Comment by rin67630** [comment]
It wolud have been great, if you could take a look a ser2net compatibilty with ptys. 
I will open a dedicated issue with that topic.

**Comment by cminyard** [comment]
I actually tried ser2net with WSL and it seems to work.  At least WSL2.
