### ISSUE TITLE
Ser2net ability to handle pseudo-serial ports.

### ISSUE THREAD

**Issue by rin67630** [cminyard/ser2net#24]
Linux offers the ability to provide simulated serial ports as /dev/pty.
ser2net will accept these ports in /etc/ser2net.conf and run with this configuration without issuing errors, however without function either.
Could you please take a look, if providing ser2net compatibility with /dev/ptys would have been a big effort or only a minor change?
Thank you!

**Comment by cminyard** [comment]
On Tue, Feb 25, 2020 at 07:42:41PM -0800, RIN67630 wrote:
> Linux offers the ability to provide simulated serial ports as /dev/pty.
> ser2net will accept these ports in /etc/ser2net.conf and run with this configuration without issuing errors, however without function either.
> Could you please take a look, if providing ser2net compatibility with /dev/ptys would have been a big effort or only a minor change?
> Thank you!

I'm not sure exactly what you are asking for.  There are two sides to a
pty: the client side and the server side, and neither make any sense for
normal ser2net usage.  Can you be more detailed in what you are trying
to accomplish?

-corey

**Comment by rin67630** [comment]
I must currently use a proprietary closed software that expects a data feed from a real serial port.
It has also the option to get this data from ser2net, which works fine if forwarding a real serial port.

On the other side I must provide a middleware that reads and transforms the data coming from the serial port. That middleware writes to a /dev/pts which in turn provides a pseudo serial port /dev/pty containing the data. This data is correctly shown using e.g. minicom. 

If I configure ser2net to use this /dev/pty "serial port", it will not issue any error, but does not forward the data as it does with a hardware serial port.
I must currently use two interconnected USB hardware ports (out-in) to get it running, that is not elegant.

**Comment by cminyard** [comment]
Ok, I am still not completely understanding.  You have a program you wrote that creates a pty.  I assume you pass the child side of the pty to the proprietary program, since you get a device name for that.  How do you pass the master side to ser2net?  There's no device there.

But I have three options for you:

- You could modify your middleware program to provide network access to the pty.  Then you wouldn't need ser2net, simplifying things a bit.  But I think I'm missing something.
- I have a library named gensio that provides access to all kinds of stream I/O.  (It's what the new version of ser2net uses for I/O.)  One option is a pty, but currently it will only run a program in the pty.  It would be easy enough to modify the existing class or write a new gensio class to open a pty and extract the device.  The trouble is there's no easy way to get the device name out of ser2net and to some other program.  You might consider using this library if you go with the first option, though.  With the above modification, you could take one of the example programs and just tweak it a bit.
- I have a simulated serial port kernel module that I use for testing.  It's at https://github.com/cminyard/serialsim.  It's basically a built-in version of what you are doing with the USB serial devices, you get a bunch of /dev/ttyPIPEA<n> and /dev/ttyPIPEB<n> simulated serial ports that are connected to each other (including modem signalling, and it does simulate the speed).  The trouble with this is that you have to recompile it for every new kernel version that gets installed in your system, and you may run into issues if you system requires signed kernel modules.  The recompile can be automated at boot.  I need to get it into the main kernel, but the process is a bit painful.

Hopefully this will give you something useful, or spur on some new ideas.

**Comment by rin67630** [comment]
Currently the black box program I am feeding to is accepting either 
-a /dev/ttyUSBx or /dev/ttySx as _real_ serial ports or
-a port number for a connection with ser2net 

Frankly the best way would have been for me to let my Python script behave exactly like ser2net and provide the same UDF stream that you are providing. But I must admit to be to dumb to achieve that in a way that the black box program would admit running for the bidirection toal communication. I could not find any detailed documentation on what is required to masquerade ser2net with success. 

So I retuned to use the original and have just entered the /dev/pts... data in ser2net.conf and had expected it to work.
Additionally I am doing all that for a nonprofit association and the finished solution should be accessible to people with low computer literacy. Having something you need to compile into is not an option.

**Comment by cminyard** [comment]
On Mon, Mar 02, 2020 at 04:14:43AM -0800, RIN67630 wrote:
> Currently the black box program I am feeding to is accepting either 
> -a /dev/ttyUSBx or /dev/ttySx as _real_ serial ports or
> -a port number for a connection with ser2net 

So you have a program that connects to either a serial port (with
specific fixed names) or that will initiate a TCP connection to a
specific port.

> 
> Frankly the best way would have been for me to let my Python script behave exactly like ser2net and provide the same UDF stream that you are providing. But I must admit to be to dumb to achieve that in a way that the black box program would admit running for the bidirection toal communication. I could not find any detailed documentation on what is required to masquerade ser2net with success. 

And you have a python program you have written that talks to the black
box program.  I'm fairly sure you don't need or want ser2net in this.
I'm guessing your python program currently talks to a serial port, and
you have modified it to create a pty that you were hoping to have
ser2net talk to to bridge the gap between the program and the pty.

If that is the case, the easiest possible solution I can think of is to
create a symbolic link from /dev/pty<x> to /dev/ttyS<y>.  If the black
box program will accept that, then you should be set.

The other possible solution is to do the network I/O in your python
program.  There are good examples at https://pymotw.com/3/.  (/2/ for
python 2)  If you want to know how to handle multiple data streams at
the same time, that same site has info on the asyncio module.  Or
asyncore for python 2.  Or you can use multiple threads.

-corey

**Comment by rin67630** [comment]
"If that is the case, the easiest possible solution I can think of is to
create a symbolic link from /dev/pty<x> to /dev/ttyS<y>.  If the black
box program will accept that, then you should be set."
I have tried that, without success. It don't work as ser2net will not work with that symlink as well.
"The other possible solution is to do the network I/O in your python
program."
That is surely the royal way to do it. 
I just lack the info required to masquerade exactly ser2net in every configuration. Do you have a description of your network protocol?

**Comment by cminyard** [comment]
On Mon, Mar 02, 2020 at 08:59:31AM -0800, RIN67630 wrote:
> "If that is the case, the easiest possible solution I can think of is to
> create a symbolic link from /dev/pty<x> to /dev/ttyS<y>.  If the black
> box program will accept that, then you should be set."
> I have tried that, without success. It don't work as ser2net will not work with that symlink as well.

That tells me the problem probably isn't in ser2net, it lies someplace
else.

> "The other possible solution is to do the network I/O in your python
> program."
> That is surely the royal way to do it. 
> I just lack the info required to masquerade exactly ser2net in every configuration. Do you have a description of your network protocol?

There is no network protocol (unless you enable telnet, which you
shouldn't be doing in this case).  It is raw bytes on the socket
transferred to raw bytes on the serial port, and vice versa.

-corey

**Comment by cminyard** [comment]
No comments for a while, so I assume you have a fix for this.  Please re-open if you still have an issue.  Thanks.
