### ISSUE TITLE
Add support for arbitrary baudrates

### ISSUE THREAD

**Issue by gmarull** [cminyard/ser2net#6]
I'm using an FTDI device (USB/Serial) with a non-standard baudrate (1250000). I can't use ser2net because it refuses such baudrate. I can work on adding support for arbitrary baudrates if that sounds useful.

**Comment by cminyard** [comment]
On 07/27/2018 06:26 AM, Gerard Marull-Paretas wrote:
>
> I'm using an FTDI device (USB/Serial) with non-standard baudrate 
> (1250000). I can't use ser2net because it refuses such baudraye. I can 
> work on adding support for arbitrary baudrates if that sounds useful.
>

If there is not a termios setting for a baud rate, how do you set it?

-corey

**Comment by gmarull** [comment]
Custom baudrates are platform dependent, for Linux and macOS you can do this:

https://github.com/gmarull/sercomm/blob/master/sercomm/posix/comms.c#L351

I will give it a try on `ser2net`

**Comment by gmarull** [comment]
@cminyard Here you can find an initial working code:

https://github.com/gmarull/ser2net/commit/1d447fcde8a1c92b9dc7e2f36c07dbaaec674eae

Note that I have not modified the config parser (which I guess needs to support any baudrate). The header def/undef *hack* is because `termios` structure is redefined in the `asm/termbits.h` header.

**Comment by cminyard** [comment]
Ok, I did this.  It was fairly unpleasant because Linux is a mess here.  It's also done in the gensio library, ser2net doesn't handle this stuff any more in ser2net 4.x.

There is a new parameter to the serialdev gensio, custspeed, that enables the function to avoid issues with it being a surprise to users that are not expecting it.

This is in the gensio git now and should be available in the next gensio release.
