### ISSUE TITLE
Transmitting binary data over ser2net

### ISSUE THREAD

**Issue by gbernaldo82** [cminyard/ser2net#91]
Hi, good afternoon!

I have been using ser2net for two years without any problem (altought mostly for sending and receiving text data) and now I need to communicate 1 software made by my with a device which only understands binary data and I wonder if is it possible to use ser2net for this kind of device. The device is pluuged to a raspberry pi throught a rs232 cable. Is it possible? 

Thank you in advance!

**Comment by cminyard** [comment]
Well, this isn't exactly an issue, it's a question.  But yes, you can use ser2net to transfer binary data.  Some caveats:

If you use a direct TCP connection, with no telnet, and the connection parameters support binary (n81, for instance) it will just work.

If you use telnet, you can still do binary, but you have to implement the telnet protocol on the other end.  (You can use the gensio library for this; it's what ser2net is based on.)  This gives you the ability to control the serial port's settings if you enable rfc2217, but otherwise is unnecessary.
