### ISSUE TITLE
setportconfig respond unknown command error in admin interface

### ISSUE THREAD

**Issue by kenvaid** [cminyard/ser2net#95]
I want use admin interface to control port configuration, but when i type setportconfig command, it respond error:
```
  port: rs485-8
  accepter: tcp,3010
  enable state: on
  timeout: 0
  device: serialdev,/dev/ttyWK3,57600N81
  device config: 57600N81,CLOCAL
  tcp to device state: waiting input
  device to tcp state: waiting input
  bytes read from device: 0
  bytes written to device: 0
-> setportconfig rs485-8 9600N81
error: Unknown command - setportconfig
```
I use ser2net version: 4.3.11, is it setportconfig command not support in this version ?

**Comment by cminyard** [comment]
That command is no longer supported.  It was going to be really hard to implement like it was implemented, and the command seemed to me to be of little value because the change was only temporary and might lead to confusion.

You have rfc2217 so you can control it over for a single session over telnet and you can modify the yaml file and send a kill -1 to ser2net to have it re-read the config without stopping anything currently in use.

It would be relatively easy to implement a command that let you replace the device gensio (You'd have to put in "serialdev,device,..."  If that would be useful, I could add it.

**Comment by kenvaid** [comment]
Thanks for your explanation, I think I would use the yaml file to change the serialdev config.
